apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-prep-lab.fullname" . }}
  labels:
    {{- include "devops-prep-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "devops-prep-lab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}